//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelUser
    {
        public int Id { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
