//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public Nullable<int> SenderId { get; set; }
        public Nullable<int> ChannelId { get; set; }
        public string DisplayName { get; set; }
        public Nullable<bool> Sent { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<bool> Seen { get; set; }
        public Nullable<System.DateTime> DateSeen { get; set; }
        public string Content { get; set; }
        public Nullable<int> ReceiverID { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual tblEmployee tblEmployee { get; set; }
    }
}
